title: Mohammed Zuhaib
logo: /assets/img/Zuhaib.jpeg
description: 875 Ali Miyan Road 1st Stage Rajivnagar Mysore 570019 
phone: +919620245283 
email: zuhu2195@gmail.com
linkedin: https://www.linkedin.com/in/mohammed-zuhaib-zuhu111/

theme: jekyll-theme-minimal
