title: Mohammed Zuhaib
logo: /assets/img/Zuhaib.jpeg
description: Software Developer
email: zuhu2195@gmail.com 
linkedin: https://www.linkedin.com/in/mohammed-zuhaib-zuhu111/
theme: jekyll-theme-minimal
